name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  actions: read
  security-events: read
  statuses: read
  packages: read
  deployments: read

jobs:
  release:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci --no-audit --no-fund

      - name: Build Electron app
        run: npm run build

      - name: Debug Token Information
        run: |
          echo "PAT Token available: ${{ secrets.PERSONAL_ACCESS_TOKEN != '' }}"
          echo "Default GitHub Token available: ${{ secrets.GITHUB_TOKEN != '' }}"
          echo "Repository: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"
          echo "Ref: ${{ github.ref }}"
          echo "Attempting to use PAT first, fallback to GITHUB_TOKEN"
          if [ -n "$GH_TOKEN" ]; then
            echo "✅ GH_TOKEN is set (length: ${#GH_TOKEN})"
          else
            echo "❌ GH_TOKEN is empty or not set"
          fi
          if [ -n "$GITHUB_TOKEN" ]; then
            echo "✅ GITHUB_TOKEN is set (length: ${#GITHUB_TOKEN})"
          else
            echo "❌ GITHUB_TOKEN is empty or not set"
          fi
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up environment variables
        run: |
          if [ -n "$PAT_TOKEN" ]; then
            echo "Using Personal Access Token"
            echo "GH_TOKEN=$PAT_TOKEN" >> $GITHUB_ENV
            echo "GITHUB_TOKEN=$PAT_TOKEN" >> $GITHUB_ENV
          else
            echo "Using default GitHub Token"
            echo "GH_TOKEN=$DEFAULT_TOKEN" >> $GITHUB_ENV
            echo "GITHUB_TOKEN=$DEFAULT_TOKEN" >> $GITHUB_ENV
          fi
        env:
          PAT_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          DEFAULT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Publish to GitHub Releases
        run: npx electron-builder --publish always --win

  test-build:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
    timeout-minutes: 15

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci --no-audit --no-fund

      - name: Test build
        run: npm run build 